---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: debian/jessie64
    memory: 2048
    provider_override_args:
      # Requires vagrant plugin "vagrant-disksize"
      - "disksize.size = '50GB'"
      - "vm.network 'forwarded_port', guest: 80, host: 8080"
      - "vm.network 'forwarded_port', guest: 443, host: 8443"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
